"""


Remove Element

Given an integer array `nums` and an integer `val`, remove all occurrences of `val` in `nums` **in-place**. The order of the elements may be changed. Then return _the number of elements in _`nums`_ which are not equal to _`val`. Consider the number of elements in `nums` which are not equal to `val` be `k`, to get accepted, you need to do the following things: - Change the array `nums` such that the first `k` elements of `nums` contain the elements which are not equal to `val`. The remaining elements of `nums` are not important as well as the size of `nums`. - Return `k`. **Custom Judge:** The judge will test your solution with the following code: int[] nums = [...]; // Input array int val = ...; // Value to remove int[] expectedNums = [...]; // The expected answer with correct length. // It is sorted with no values equaling val. int k = removeElement(nums, val); // Calls your implementation assert k == expectedNums.length; sort(nums, 0, k); // Sort the first k elements of nums for (int i = 0; i < actualLength; i++) { assert nums[i] == expectedNums[i]; } ``` If all assertions pass, then your solution will be **accepted**.   **Example 1:** **Input:** nums = [3,2,2,3], val = 3 **Output:** 2, nums = [2,2,_,_] **Explanation:** Your function should return k = 2, with the first two elements of nums being 2. It does not matter what you leave beyond the returned k (hence they are underscores). ``` **Example 2:** **Input:** nums = [0,1,2,2,3,0,4,2], val = 2 **Output:** 5, nums = [0,1,4,0,3,_,_,_] **Explanation:** Your function should return k = 5, with the first five elements of nums containing 0, 0, 1, 3, and 4. Note that the five elements can be returned in any order. It does not matter what you leave beyond the returned k (hence they are underscores). ```   **Constraints:** - `0 <= nums.length <= 100` - `0 <= nums[i] <= 50` - `0 <= val <= 100`


Given an integer array nums and an integer val, remove all occurrences of val in nums in-place. The order of the elements may be changed. Then return _the number of elements in nums which are not equal to _val.

Consider the number of elements in nums which are not equal to val be k, to get accepted, you need to do the following things:

Change the array nums such that the first k elements of nums contain the elements which are not equal to val. The remaining elements of nums are not important as well as the size of nums.
Return k.
Custom Judge:

The judge will test your solution with the following code:

int[] nums = [...]; // Input array int val = ...; // Value to remove int[] expectedNums = [...]; // The expected answer with correct length. // It is sorted with no values equaling val.

int k = removeElement(nums, val); // Calls your implementation

assert k == expectedNums.length; sort(nums, 0, k); // Sort the first k elements of nums for (int i = 0; i < actualLength; i++) { assert nums[i] == expectedNums[i]; }

If all assertions pass, then your solution will be accepted.

 

Example 1:

Input: nums = [3,2,2,3], val = 3 Output: 2, nums = [2,2,,] Explanation: Your function should return k = 2, with the first two elements of nums being 2. It does not matter what you leave beyond the returned k (hence they are underscores).

Example 2:

Input: nums = [0,1,2,2,3,0,4,2], val = 2 Output: 5, nums = [0,1,4,0,3,,,_] Explanation: Your function should return k = 5, with the first five elements of nums containing 0, 0, 1, 3, and 4. Note that the five elements can be returned in any order. It does not matter what you leave beyond the returned k (hence they are underscores).

 

Constraints:

0 <= nums.length <= 100
0 <= nums[i] <= 50
0 <= val <= 100
Need help or want more practice?



Example 1:
Input:
{"nums": [3, 2, 2, 3], "val": 3}
Output:
2
Explanation:
Basic functionality: Removes all 3s, leaving two 2s. Tests simple removal and correct count.

Example 2:
Input:
{"nums": [0, 1, 2, 2, 3, 0, 4, 2], "val": 2}
Output:
5
Explanation:
Basic functionality: Removes all 2s, leaving five elements. Checks handling of multiple removals and order flexibility.

Example 3:
Input:
{"nums": [], "val": 1}
Output:
0
Explanation:
Edge case: Empty array input. Should return 0 as there are no elements to remove.

Example 4:
Input:
{"nums": [1, 1, 1, 1], "val": 1}
Output:
0
Explanation:
Edge case: All elements are equal to val. Should remove all and return 0.

Example 5:
Input:
{"nums": [5, 6, 7, 8, 5, 9, 10, 5, 11, 12, 13, 5, 14, 15, 16, 17, 5, 18, 19, 20], "val": 5}
Output:
15
Explanation:
Generated by LLM corrector on 2025-10-10T16:10:36.943941

Need help or want more practice?
"""

import time


def remove_element(nums, val):
    write = 0
    for read in range(len(nums)):
        if nums[read] != val:
            nums[write] = nums[read]
            write += 1

    for i in range(write, len(nums)):
        nums[i] = None

    return write


def validate_result(original_nums, val, mutated_nums, k, expected_k, expected_nums):
    if k != expected_k:
        return False, f"expected k={expected_k}, got {k}"

    if sorted(mutated_nums[:k]) != sorted(expected_nums[:k]):
        return (
            False,
            f"expected first {k} values to match {expected_nums[:k]}, got {mutated_nums[:k]}",
        )

    if any(value == val for value in mutated_nums[:k]):
        return False, f"value {val} still present in first {k} positions"

    if mutated_nums[k:] != expected_nums[k:]:
        return False, f"expected tail {expected_nums[k:]}, got {mutated_nums[k:]}"

    if len(original_nums) != len(mutated_nums):
        return False, "array length changed"

    return True, "valid"


tests = [
    ([], 0, 0, []),
    ([3, 2, 2, 3], 3, 2, [2, 2, None, None]),
    ([0, 1, 2, 2, 3, 0, 4, 2], 2, 5, [0, 0, 1, 3, 4, None, None, None]),
    ([1, 2, 3, 4], 5, 4, [1, 2, 3, 4]),
    ([7, 7, 7], 7, 0, [None, None, None]),
    ([4], 4, 0, [None]),
    ([4], 3, 1, [4]),
    ([2, 2, 2, 3, 3, 2], 2, 2, [3, 3, None, None, None, None]),
    ([0, 1, 0, 1, 0], 0, 2, [1, 1, None, None, None]),
    ([1, 1, 2, 2, 3, 3], 2, 4, [1, 1, 3, 3, None, None]),
    ([50, 0, 50, 1, 50], 50, 2, [0, 1, None, None, None]),
    ([5, 6, 5, 6, 5, 6], 6, 3, [5, 5, 5, None, None, None]),
]


def run_basic_tests():
    for nums, val, expected_k, expected_nums in tests:
        original = nums[:]
        print(f"nums={original}, val={val}")
        start = time.perf_counter()
        k = remove_element(nums, val)
        end = time.perf_counter()

        is_valid, message = validate_result(
            original, val, nums, k, expected_k, expected_nums
        )

        print(f"time={(end - start):.6f}s")
        print(True if is_valid else {"k": k, "nums": nums, "error": message})


if __name__ == "__main__":
    try:
        run_basic_tests()
    except NotImplementedError as exc:
        print(exc)
